name: Django CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # =========================
  # 1. CI - Test Application
  # =========================
  test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./likith_kitchen

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test


  # =========================
  # 2. Build and Push Docker
  # =========================
  build:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Build Docker Image
        run: |
          docker build -t likithkumaro/likith-kitchen:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push likithkumaro/likith-kitchen:latest


  # =========================
  # 3. CD - Deploy Application
  # =========================
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull Latest Docker Image
        run: |
          docker pull likithkumaro/likith-kitchen:latest

      - name: Stop Old Container
        run: |
          docker stop likith-kitchen || true

      - name: Remove Old Container
        run: |
          docker rm likith-kitchen || true

      - name: Start New Container
        run: |
          docker run -d \
            -p 8000:8000 \
            --name likith-kitchen \
            likithkumaro/likith-kitchen:latest

      - name: Health Check
        run: |
          sleep 5
          curl --fail http://localhost:8000