name: Django CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./likith_kitchen

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test

      - name: Build Docker Image
        working-directory: .
        run: |
          docker build -t likith-kitchen:ci .

      - name: Run Docker Container
        working-directory: .
        run: |
          docker run -d \
            --name likith-kitchen-ci \
            -p 8000:8000 \
            likith-kitchen:ci

      - name: Wait for Django
        run: |
          sleep 5

      - name: Check Docker Container
        working-directory: .
        run: |
          docker ps

      - name: Show Docker Logs
        if: always()
        working-directory: .
        run: |
          docker logs likith-kitchen-ci

      - name: Stop Docker Container
        if: always()
        working-directory: .
        run: |
          docker stop likith-kitchen-ci || true